theme: jekyll-theme-slate
title: Dark engine mod manager
description: A mod manager for all Dark engine games made by Looking Glass Studios

show_downloads: ["true"]
github:
  executable_url: https://github.com/pshjt/dmm/releases/latest/download/dmm.exe

exclude: [Gemfile,Gemfile.lock]